### ISSUE TITLE
Sync delay

### ISSUE THREAD

**Issue by retog** [nikku/wuffle#37]
When I add change an issue on GitHub it takes a long time (more than 10 minutes) till this is visible in wuffle. In the repository settings in GitHub I don't see a webhook notifying my wuffle host. For details about my settings, see https://github.com/nikku/wuffle/issues/32. Wuffle is configured to have Read/Write access to Repository webhooks (Manage the post-receive hooks for  repository) and is subscribed to Issues/Milestones and PR events.

**Comment by retog** [comment]
Thanks @nikku, I've double-checked the settings.

![image](https://user-images.githubusercontent.com/110756/61365227-a7c0ea00-a887-11e9-93a6-4ebc076ee7bf.png)

What I don't find in the UI but is uncommented in https://github.com/nikku/wuffle/blob/master/packages/app/app.yml are `create` and `push`.

I've enabled the app for all my repositories

![image](https://user-images.githubusercontent.com/110756/61365514-2cac0380-a888-11e9-9231-9fe548bf863b.png)

I've added a public repository for testing https://github.com/retog/wuffle-test

Some issues of this repository are visible on https://wuffle.factsmission.org/board, however the issue https://github.com/retog/wuffle-test/issues/3 which I created 10 minutes ago isn't visible yet. Feel free to add more issues if you want to test.

I really appreciate your help getting this great piece of software running.

**Comment by retog** [comment]
Found somtheing in the log
```

  Error: signature does not match event payload and secret


      at verifyAndReceive (/app/packages/app/node_modules/@octokit/webhooks/middleware/verify-and-receive.js:9:19)


      at getPayload.then (/app/packages/app/node_modules/@octokit/webhooks/middleware/middleware.js:46:14)


      at process._tickCallback (internal/process/next_tick.js:68:7)


10:26:49.668Z  INFO http: POST / 400 - 1.74 ms (id=62af1310-a87d-11e9-9172-cdff8b05e1e3)


10:27:14.751Z  INFO http: GET /board 200 - 3.40 ms (id=002a02b3-18a4-47b7-bdcf-39e26e917fef)


```

I'll check.

**Comment by retog** [comment]
That was it! Sorry for not having noticed this before. re-entering the secret fixed things. Thanks for your time.

**Comment by nikku** [comment]
Please double check your permissions section. Correctly setup permissions will enable the required events, specifically a `Create` event you can subscribe to.

**Comment by joannenolan-sky** [comment]
That is probably a permission error, so that the issue is only picked up when you do a `sync`.
Have you checked your permissions See my PR #36 . It might help. Also I would copy the `WEBHOOK_SECRET` into your Github App again, as that is what I did when I got that error to fix it

**Comment by retog** [comment]
@joannenolan-sky repasting the secret solved the problem. Thanks!
